# -*- coding: utf-8 -*-
# Copyright (c) XiMing Xing. All rights reserved.
# Author: XiMing Xing

from setuptools import setup, find_packages

setup(
    name='pytorch_svgrender',
    version="0.1.0",
    packages=find_packages(where="."),  # カレントディレクトリを指定
    package_dir={"": "."},  # パッケージのルートディレクトリを指定
    install_requires=[
        'hydra-core',
        'omegaconf',
        'freetype-py',
        'shapely',
        'svgutils',
        'cairosvg',
        'opencv-python',
        'scikit-image',
        'matplotlib',
        'visdom',
        'wandb',
        'beautifulsoup4',
        'triton',
        'numba',
        'numpy',
        'scipy',
        'scikit-fmm',
        'einops',
        'timm',
        'fairscale==0.4.13',
        'accelerate',
        'transformers',
        'safetensors',
        'datasets',
        'easydict',
        'scikit-learn',
        'pytorch_lightning==2.1.0',
        'webdataset',
        'ftfy',
        'regex',
        'tqdm',
        'diffusers==0.32.2',
        'svgwrite',
        'svgpathtools',
        'cssutils',
        'torch-tools',
        'git+https://github.com/openai/CLIP.git',
    ],
    python_requires=">=3.7",
    author='Ximing Xing, Juncheng Hu et al.',
    author_email='ximingxing@gmail.com',
    description='SVG Differentiable Rendering: Generating vector graphics using neural networks.',
    long_description=open("README.md").read() if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    keywords=[
        'Artificial Intelligence',
        'AIGC',
        'Generative Models',
        'SVG Generation',
    ],
    url='https://github.com/ximinng/PyTorch-SVGRender',
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
